const x = 10;

try {
    if(x == 10) {
        console.log("Tudo certo!")
    }
} catch (err) {
    console.log(`Erro: ${err}`)
}